# .github/workflows/android.yml

name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download and install Gradle 8.0.2
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
          unzip -q gradle-8.0.2-bin.zip -d gradle
          echo "GRADLE_HOME=${{ runner.workspace }}/gradle/gradle-8.0.2" >> $GITHUB_ENV
          echo "${{ runner.workspace }}/gradle/gradle-8.0.2/bin" >> $GITHUB_PATH

      - name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
