name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # Si tienes gradlew en tu repo, descomenta estas líneas:
    #- name: Make gradlew executable
    #  run: chmod +x ./gradlew

    - name: Build debug APK
      # Si tienes gradlew, cambia "gradle" por "./gradlew"
      run: gradle assembleDebug --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
